### ISSUE TITLE
Seems like selecting a specific luftdaten sensor provides no data

### ISSUE THREAD

**Issue by Bavoc** [gruijter/com.gruijter.openaq#3]
Hi,

I've just started using this app in homey. 
And I've just set up my own luftdaten sensor (https://maps.sensor.community/?nowind#14/51.0254/5.4677)
So, first of all, many thanks!

I think a found a bug:
When adding "LD moniter@Homey", the "device" show results and actually seems to show my data.
But, when I specifically select my own sensor (or another nearby) I don't receive any data on that device in homey.

Maybe something you can look into?

Thanks!

**Comment by Bavoc** [comment]
Hi,

I also have an additional question/issue
Since I want to use this data in our home ventilation (since neighbors are burning a lot of rubbish and causing local air pollution) I need the data as recent as possible, and looking at the data it didn't seem the most recent. (directly from my sensor, in luftdaten and in homey)
So I started to investigating the luftdaten API.
It seems like the api returns the last 2 measurements per station, and in homey, even though it is reset every minute (setting) I seem to see older data.

**Can it be that you are not using 'the most recent' entry from the reply of the api of luftdaten?**

Update: the api _sometimes_ provides multiple results at once. So probably I only get an older value when multiple measurements are included.

Here's an example api reply from [my sensor](http://data.sensor.community/airrohr/v1/filter/area=51.0270988,5.4685663,1) as well as a screenshot from Homey app:
![screenshot_Homey_APIresponse2](https://user-images.githubusercontent.com/55828898/101796740-89592f80-3b09-11eb-8576-97061328cf53.png)
[api_response_2.txt](https://github.com/gruijter/com.gruijter.openaq/files/5673999/api_response_2.txt)

and one other response:
![api_resp_part1](https://user-images.githubusercontent.com/55828898/101795386-20bd8300-3b08-11eb-8f38-e0eb68f97a03.JPG)
![api_resp_part2](https://user-images.githubusercontent.com/55828898/101795390-21eeb000-3b08-11eb-9eed-8dee5e3a23f9.JPG)
![api_resp_part3](https://user-images.githubusercontent.com/55828898/101795391-22874680-3b08-11eb-84df-98a499dba45e.JPG)
[api_response.txt](https://github.com/gruijter/com.gruijter.openaq/files/5673929/api_response.txt)

Many thanks!
Bavo

**Comment by gruijter** [comment]
Hi Bavoc. Thx for the feedback and your research so far.

on short notice I have no time to look into this, but I will keep it on my backlog.

**Comment by Bavoc** [comment]
Thx!

**Comment by gruijter** [comment]
I just fixed both issues. Please install from here and let me know if it now works correctly for you:

https://homey.app/nl-nl/app/com.gruijter.openaq/Outdoor-AirQuality/test/

**Comment by Bavoc** [comment]
Hi,

first of all, Many thanks and Happy New Year!

only positive feedback so far:
1) newest data = Good! I've just tested and data seems live/newest data from my sensor.
much better/highly appreciated!

2) adding a specific sensor = works good as well!

My thanks!
Bavo
_I'll keep using this test version for a while, if I notice something strange, I'll let you know in the upcoming days, but it looks really good!_

**Comment by gruijter** [comment]
Super! I'll close the issue. Reopen it if you do find issues.
