### ISSUE TITLE
Feature request - temperature & humidity values

### ISSUE THREAD

**Issue by Bavoc** [gruijter/com.gruijter.openaq#5]
Hi,

How about making temperature and humidity available for luftdaten sensors?
The values are included in the API result. (I don't know if the other sensors also provide these values, but I guess so)
It would seem like a nice add on for me, especially since I own a sensor so I wouldn't need an additional outdoor temp/humidity sensor if that would be included.

No urgency, but a nice to have ;)

**Comment by gruijter** [comment]
Yes, I think I can add that dynamically if the data is there. On a next update I will try to include it.

**Comment by Bavoc** [comment]
nice! looking forward 👍

**Comment by gruijter** [comment]
I'm looking into this now. But there is a problem for me in the API. The PM2.5/PM10 data is coming from a different 'sensor' then the humidity/temperature. So I do not know how I can match the 2 sensors into one Homey sensor. Besides lat/lon information, is there any unique ID in the API results that I can use to match the two sensors together?

**Comment by Bavoc** [comment]
Good question, 
In grafana I see the "chipID" which matches. (ex. https://api-rrd.madavi.de/grafana/d/GUaL5aZMz/pm-sensors?orgId=1&var-chipID=esp8266-3144632 )
But on the api.luftdaten.info I don't see that ID (http://data.sensor.community/airrohr/v1/filter/area=51.0270988,5.4685663,1 )
There is a sensorID which is 53666 for PM and 53667 weather in my case, but I don't think it's safe to use "the next ID", think this is error prone.

Maybe it's easier to create a different device type for the temperature/humidity/pressure which you add in the same way as PM values?

**Comment by gruijter** [comment]
I am now experimenting with using the lat/lon to match them. So far this seems to be working ok for the locations I have tried.

**Comment by Bavoc** [comment]
Alright, good luck!

Op zo 25 apr. 2021 13:13 schreef gruijter ***@***.***>:

**Comment by gruijter** [comment]
Ok, I have published it as test version. Can you please test and let me know if it works?

Thx!

https://homey.app/a/com.gruijter.openaq/test/

**Comment by Bavoc** [comment]
First test looking very good!
Many thanks again!

**Comment by gruijter** [comment]
Super! I will push this version to stable then.

**Comment by gruijter** [comment]
And many thx 4 your donation! 🍻
