### ISSUE TITLE
luftdaten - No more data since 04/11 and unable to add new device - change in api?

### ISSUE THREAD

**Issue by Bavoc** [gruijter/com.gruijter.openaq#6]
Hi,
I do not get updates luftdaten values any more, same goes for someone else in the forum:
have a look at https://community.homey.app/t/app-pro-outdoor-airquality-monitor-luftdaten/17548/68.

Also not possible to add new devices for luftdaten.

suppose it has to do with:
`Important: The client needs to send a user agent header. In the best case the user agent string should give us a chance to contact the source of i.e. excessive requests. (since 2022/11/04)`
[luftdaten api wiki](https://github.com/opendata-stuttgart/meta/wiki/EN-APIs )

**Comment by gruijter** [comment]
fixed in v2.2.0
